---

- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Installing brew formulas {{ brew_formulas }}
  community.general.homebrew:
    name: "{{ brew_formulas }}"
    state: present
