---

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Installing brew formulas {{ brew_formulas }}
  homebrew:
    name: "{{ brew_formulas }}"
    state: present

- name: Install Google Chrome
  homebrew_cask:
    name: google-chrome
    state: present

- name: Install ITerm 2
  homebrew_cask:
    name: iterm2
    state: present
